# Generated by Django 2.2.28 on 2023-06-21 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=200)),
                ('temps_cuisson', models.CharField(max_length=100)),
                ('temps_preparation', models.CharField(max_length=100)),
                ('ingredients', models.TextField()),
                ('etapes_preparation', models.TextField()),
                ('difficulte', models.IntegerField(choices=[(1, 'Facile'), (2, 'Moyenne'), (3, 'Difficile')])),
                ('nombre_personnes', models.PositiveIntegerField()),
                ('date_creation', models.DateTimeField(default=django.utils.timezone.now)),
                ('auteur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Categorie')),
            ],
        ),
    ]
